language: c
compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl libssl-dev asterisk

install: true

script:
  - sudo make cert
  - sudo make
  - sudo make install
